[package]
name = "my-first-burn-model"
version = "0.1.0"
edition = "2021"

[lints.rust]
unsafe_code = "forbid"
unused = "allow" # For exploratory dev.

[dependencies]
burn = { version = "0.13.2", features = ["train", "wgpu", "vision"] }
